### ISSUE TITLE
Feedback for Future Improvements

### ISSUE THREAD

**Issue by Asher978** [dmartss/Project-2-Life-Tracker#1]
Great Job with the functionality of your app. I really like your topic behind the app. I would look more into how people will use your app for their benefit. Below are just few suggestions from me:

- [ ] A page where User can view weekly input values. Maybe in a table format

- [ ] Maybe sourcing another API where the user weekly inputs are fed into that API and in return you can get some sort of a quick Health check up based on User's consumption of calories, sleep and exercise.

- [ ] Separating the USER input in two sections for a better user experience
  *  Food intake
  *  Activities (sleep, exercise, etc)

**Comment by dmartss** [comment]
Thanks Asher, 

I appreciate the feedback. Like we discussed, your first point was the first feature I wanted to add if I had  the time. 

Your second idea is really creative and something I hadn't even thought of. Wish I had that input last week so I could have implemented it, that probably would have been manageable to fit in time. 

To your last point, that was what I meant to do from the beginning, however once I was able to display both tables on the same page, along with making them full functional (editable and deletable on the same screen) after many errors.. I needed to move on to other functionality features. I was planning on going back to it if I had the time to revisit that feature, yet once again I did not have the opportunity to do so. 

Overall great suggestions, I totally agree.
